# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-08 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.IntegerField(default=0)),
                ('cid', models.CharField(default='', max_length=255)),
                ('cmt', models.TextField(default='')),
                ('label', models.IntegerField(default=3)),
                ('author', models.CharField(default='', max_length=255)),
                ('period', models.CharField(default='', max_length=255)),
                ('randnum', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
