# Generated by Django 2.2 on 2019-05-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yougam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='capture_path',
            field=models.CharField(default='SOME STRING', max_length=400),
        ),
    ]
