# Generated by Django 2.2 on 2019-05-14 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yougam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='label6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='sentiment_anger',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='sentiment_fear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='sentiment_happy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='sentiment_neutral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='sentiment_sad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='sentiment_surprise',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yougam.Video'),
        ),
        migrations.CreateModel(
            name='ReplyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('label', models.IntegerField(default=3)),
                ('label6', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('like', models.IntegerField(default=0)),
                ('randnum', models.IntegerField(default=1)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yougam.Comment')),
            ],
        ),
    ]
