# Generated by Django 2.2.1 on 2019-05-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yougam', '0002_auto_20190514_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_sentiment', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('img_path', models.ImageField(upload_to='')),
            ],
        ),
    ]
