# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-09 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yougam', '0002_auto_20190509_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='label6',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='video',
            name='sentiment_anger',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='sentiment_fear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='sentiment_happy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='sentiment_neutral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='sentiment_sad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='sentiment_surprise',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yougam.Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
