# Generated by Django 2.2.1 on 2019-05-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yougam', '0003_timelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
