# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yougam', '0003_auto_20190510_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.IntegerField(default=0),
        ),
    ]
