# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-12 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yougam', '0005_auto_20190510_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('label', models.IntegerField(default=3)),
                ('label6', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('like', models.IntegerField(default=0)),
                ('randnum', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replydata',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yougam.Comment'),
        ),
    ]
