# Generated by Django 2.2.1 on 2019-05-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yougam', '0005_piechart'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('json_data', models.CharField(max_length=400)),
            ],
        ),
    ]
