# Generated by Django 2.2.1 on 2019-05-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yougam', '0006_webcam'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcam',
            name='video_path',
            field=models.CharField(default='SOME STRING', max_length=400),
        ),
    ]
